name: Devopx Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy stage..."

  promote:
    name: Promote Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running promote stage..."
