name: Deploy to Dev

on:
  push:
    branches:
      - main
    paths:
      - env/dev/manifest.json

jobs:
  deploy:
    runs-on: windows-2019
    env:
      target_env: dev
      target_host: dev-host

    steps:
      - uses: actions/checkout@v3

      - name: Show IP config
        run: ipconfig

      - name: Deploy to Dev
        shell: pwsh
        run: |
          Write-Host "Deploying  using powershell script with the service account added to AD domain of deployment server"
          Write-Host "Deployment to environment: $env:target_env successful"
          # .\scripts\deploy.ps1 -Environment $env:target_env -Host $env:target_host
