name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - env/dev/manifest.json
      - env/test/manifest.json
      - env/preprod/manifest.json
      - env/prod/manifest.json

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        env: [dev, test, preprod, prod]

    if: contains(join(github.event.commits.*.modified, ' '), 'env/' + matrix.env + '/manifest.json')

    env:
      target_env: ${{ matrix.env }}
      target_host: ${{ fromJson('{"dev":"dev-host","test":"test-host","preprod":"preprod-host","prod":"prod-host"}')[matrix.env] }}

    steps:
      - uses: actions/checkout@v3

      - name: Show IP config
        run: ipconfig

      - name: List modified files
        run: echo "Modified files: ${{ join(github.event.commits.*.modified, ', ') }}"

      - name: Deploy to ${{ env.target_env }}
        shell: pwsh
        run: |
          Write-Host "Deploying to environment: $env:target_env"
          Write-Host "Deploying to host: $env:target_host"
          # Call your deploy script here
