name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - env/**/manifest.json

jobs:
  deploy-dev:
    runs-on: windows-2019
    paths:
      - env/dev/manifest.json
    env:
      target_env: dev
      target_host: dev-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Dev
        run: echo "Deploying to dev..."

  deploy-test:
    runs-on: windows-2019
    paths:
      - env/test/manifest.json
    env:
      target_env: test
      target_host: test-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Test
        run: echo "Deploying to test..."

  deploy-preprod:
    runs-on: windows-2019
    paths:
      - env/preprod/manifest.json
    env:
      target_env: preprod
      target_host: preprod-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Preprod
        run: echo "Deploying to preprod..."

  deploy-prod:
    runs-on: windows-2019
    paths:
      - env/prod/manifest.json
    env:
      target_env: prod
      target_host: prod-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Prod
        run: echo "deploying using powershell script with the service account added to AD domain of deployment server"
             eco "Deploy successful"