name: Deploy to Prod

on:
  push:
    branches:
      - main
    paths:
      - env/prod/manifest.json

jobs:
  deploy:
    runs-on: windows-2019
    env:
      target_env: prod
      target_host: prod-host

    steps:
      - uses: actions/checkout@v3

      - name: Show IP config
        run: ipconfig

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devopx-cli
        run: npm install -g devopx-cli  

      - name: Deploy to Prod
        shell: pwsh
        run: |
          echo "Deploying  using powershell script with the service account added to AD domain of deployment server"
          echo "Deployment to environment: $env:target_env successful"
          devopx post-deploy --environment "${{ github.repository }}:prod"
