name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - env/**/manifest.json  # catch all envs

jobs:
  deploy:
    runs-on: windows-2019
    strategy:
      matrix:
        env: [dev, test, preprod]
    env:
      target_env: ${{ matrix.env }}
      target_host: ${{ fromJson('{"dev":"dev-host","test":"test-host","preprod":"preprod-host"}')[matrix.env] }}

    steps:
      - uses: actions/checkout@v3

      - name: IP Config
        run: ipconfig

      - name: Deploy
        if: contains(github.event.head_commit.message, matrix.env)
        run: |
          echo "Deploying to ${{ env.target_env }} using PowerShell script with the service account added to AD domain of deployment server"
