name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - env/**/manifest.json

jobs:
  deploy-dev:
    if: ${{ contains(github.event.head_commit.url, 'env/dev/manifest.json') }}
    runs-on: windows-2019
    env:
      target_env: dev
      target_host: dev-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Dev
        run: echo "Deploying to dev..."

  deploy-test:
    if: ${{ contains(github.event.head_commit.url, 'env/test/manifest.json') }}
    runs-on: windows-2019
    env:
      target_env: test
      target_host: test-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Test
        run: echo "Deploying to test..."

  deploy-preprod:
    if: ${{ contains(github.event.head_commit.url, 'env/preprod/manifest.json') }}
    runs-on: windows-2019
    env:
      target_env: preprod
      target_host: preprod-host
    steps:
      - uses: actions/checkout@v3
      - name: IP Config
        run: ipconfig
      - name: Deploy to Preprod
        run: echo "Deploying to preprod..."
