# .github/workflows/promote-dev-to-test.yml
#name: Promote dev to Test

on:
  push:
    paths:
      - env/dev/manifest.json
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: windows-2019
    env:
      target_env: dev
      target_host: dev-host

    steps:
      - uses: actions/checkout@v3

      - name: Show IP config
        run: ipconfig

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devopx-cli
        run: npm install -g devopx-cli  

      - name: Deploy to Dev
        shell: pwsh
        run: |
          echo "Deploying  using powershell script with the service account added to AD domain of deployment server"
          echo "Deployment to environment: $env:target_env successful"
          devopx post-deploy --environment "${{ github.repository }}:dev"



  call-promote:
    name: Promote Dev to Test
    uses: ./.github/workflows/promote.yml
    with:
      from-env: dev
      to-env: test
      environment: test-approval
