# .github/workflows/promote-test-to-preprod.yml
#name: Promote Test to PreProd

on:
  push:
    paths:
      - env/test/manifest.json
    branches:
      - main   

jobs:
  deploy:
    name: Deploy to Test
    runs-on: windows-2019
    env:
      target_env: test
      target_host: test-host

    steps:
      - uses: actions/checkout@v3

      - name: Show IP config
        run: ipconfig

      - name: Deploy to Test
        shell: pwsh
        run: |
          echo "Deploying  using powershell script with the service account added to AD domain of deployment server"
          echo "Deployment to environment: $env:target_env successful"
  

  call-promote:
    name: Promote Test to Preprod
    uses: ./.github/workflows/promote.yml
    with:
      from-env: test
      to-env: preprod
      environment: preprod-approval
